# Generated by Django 2.2.4 on 2019-09-23 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursename',
            name='created_at',
        ),
    ]
