# Generated by Django 2.2.4 on 2019-09-23 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_coursename_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursename',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 23, 5, 4, 44, 159419)),
        ),
    ]
