# Generated by Django 2.2.4 on 2019-09-23 05:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190923_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursename',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 23, 5, 7, 28, 174647)),
        ),
    ]
