# Generated by Django 2.2.4 on 2019-09-23 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190923_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursename',
            name='created_at',
        ),
        migrations.AddField(
            model_name='coursename',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 23, 5, 8, 22, 334166)),
        ),
    ]
