# Generated by Django 2.2.4 on 2019-09-23 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190923_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursename',
            name='updated',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 9, 23, 5, 8, 42, 220858)),
        ),
    ]
