# Generated by Django 2.2.4 on 2019-09-25 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20190923_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursename',
            name='joined_by',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
