# Generated by Django 2.2.4 on 2019-09-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20190925_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursename',
            old_name='updated',
            new_name='created_At',
        ),
        migrations.AddField(
            model_name='coursename',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
