# Generated by Django 2.2.4 on 2019-10-05 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0011_auto_20190925_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursename',
            name='joined_by',
        ),
        migrations.AddField(
            model_name='coursename',
            name='joined_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='joined', to=settings.AUTH_USER_MODEL),
        ),
    ]
