# Generated by Django 2.2.6 on 2019-10-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20191005_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursename',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
